version: '3.8'

services:
  # O!Store Agent API (Ollama-compatible)
  # This service now connects to an external Qdrant instance.
  # Ensure your .env file contains the correct QDRANT_HOST (the IP address) and QDRANT_PORT.
  ostore-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ostore_api
    env_file:
      - .env
    ports:
      - "8008:8008"
    # 'depends_on' is removed as Qdrant is no longer managed by this compose file.
    restart: unless-stopped
    networks:
      - ostore_network
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    # Variables set here in the 'environment' block will override any values
    # set for the same variables in the .env file.
    environment:
      - QDRANT_HOST=172.27.201.105
      - QDRANT_PORT=6333

# The 'qdrant' service and its associated volume 'qdrant_data' have been removed.
networks:
  ostore_network:
    driver: bridge

